/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import entity.ChatLieu;
import entity.DanhMuc;
import entity.MauSac;
import entity.SanPham;
import entity.SanPhamBanHang;
import entity.SanPhamChiTiet;
import entity.SanPhamQuanLy;
import entity.Size;
import entity.ThuongHieu;
import java.awt.HeadlessException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import service.ChatLieuService;
import service.DanhMucService;
import service.MauSacService;
import service.QlySanPhamService;
import service.SanPhamChiTietService;
import service.SanPhamService;
import service.SizeService;
import service.ThuongHieuServicee;

/**
 *
 * @author Phan Cao
 */
public class Form_SanPham extends javax.swing.JPanel {

    DefaultTableModel model = new DefaultTableModel();
    QlySanPhamService qlsvsv = new QlySanPhamService();
    SizeService szsv = new SizeService();
    ChatLieuService clsv = new ChatLieuService();
    DanhMucService dmsv = new DanhMucService();
    SanPhamChiTietService spctsc = new SanPhamChiTietService();
    ThuongHieuServicee thsv = new ThuongHieuServicee();
    MauSacService mssv = new MauSacService();
    SanPhamService spsv = new SanPhamService();

    DefaultComboBoxModel<Size> modelCombo = new DefaultComboBoxModel<>();

    private final List<Size> listkt = szsv.getAllSize();
    private final List<DanhMuc> listdm = dmsv.getAllDanhMuc();
    private final List<MauSac> listms = mssv.getAllMauSac();
    private final List<ChatLieu> listcl = clsv.getAllChatLieu();
    private final List<ThuongHieu> listth = thsv.getAllThuongHieu();

    /**
     * Creates new form content2
     */
    public Form_SanPham() {
        initComponents();
        cboSize.setModel((DefaultComboBoxModel) modelCombo);
        fillCbbSize();
        fillCbbMauSac();
        fillCbbChatLieu();
        fillCbbThuongHieu();
        fillCbbDanhMuc();
        fillCbbTT();
//        fillCbbTrangThai();
        model = (DefaultTableModel) tblSanPham.getModel();
        LoadDataToTableSanPham();
    }

    private void fillCbbTT() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboTrangThai.getModel();
        model.removeAllElements();
        model.addElement("Đang bán");
        model.addElement("Ngừng bán");
    }

    private void fillCbbSize() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboSize.getModel();
        model.removeAllElements();

        List<Size> listCbb = szsv.getAllSize();
        for (Size size : listCbb) {
            model.addElement(size);
        }
    }

    private void fillCbbMauSac() {
        DefaultComboBoxModel modelms = (DefaultComboBoxModel) cboMauSac.getModel();
        modelms.removeAllElements();

        List<MauSac> listCbb = mssv.getAllMauSac();
        for (MauSac mauSac : listCbb) {
            modelms.addElement(mauSac);
        }
    }

    private void fillCbbChatLieu() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboChatLieu.getModel();
        model.removeAllElements();

        List<ChatLieu> listCbb = clsv.getAllChatLieu();
        for (ChatLieu chatLieu : listCbb) {
            model.addElement(chatLieu);
        }
    }

    private void fillCbbDanhMuc() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboDanhMuc.getModel();
        model.removeAllElements();

        List<DanhMuc> listCbb = dmsv.getAllDanhMuc();
        for (DanhMuc danhMuc : listCbb) {
            model.addElement(danhMuc);
        }
    }

    private void fillCbbThuongHieu() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboThuongHieu.getModel();
        model.removeAllElements();

        List<ThuongHieu> listCbb = thsv.getAllThuongHieu();
        for (ThuongHieu th : listCbb) {
            model.addElement(th);
        }
    }

//    private void fillCbbTrangThai() {
//        DefaultComboBoxModel model = (DefaultComboBoxModel) cboTrangThai.getModel();
//        model.removeAllElements();
//
//        ArrayList<SanPhamQuanLy> lst = qlsvsv.getAllSanPham();
//        for (SanPhamQuanLy th : lst) {
//            model.addElement(th.isTrangThai()==true?"Còn bán":"Không bán");
//        }
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMaSp = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTenSp = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtGia = new javax.swing.JTextField();
        txtSoLuong = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cboTrangThai = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        cboSize = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        cboMauSac = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        cboChatLieu = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        cboDanhMuc = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        cboThuongHieu = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSanPham = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        btnTimKiem = new javax.swing.JButton();
        btnHienThiLai = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Quản lý sản phẩm");

        jLabel3.setText("Nhập thông tin :");

        jLabel4.setText("Mã SP");

        jLabel5.setText("Tên SP");

        jLabel6.setText("Giá");

        txtSoLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoLuongActionPerformed(evt);
            }
        });

        jLabel7.setText("Số lượng");

        jLabel8.setText("Trạng thái");

        jLabel9.setText("Size");

        jLabel10.setText("Màu sắc");

        jLabel11.setText("Chất liệu");

        jLabel12.setText("Danh mục");

        jLabel13.setText("Thương hiệu");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cboTrangThai, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtMaSp, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                            .addComponent(txtTenSp)
                            .addComponent(txtGia)
                            .addComponent(txtSoLuong))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 211, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel9)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12))
                        .addGap(42, 42, 42)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cboMauSac, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cboChatLieu, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cboSize, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboThuongHieu, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cboDanhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cboChatLieu, cboDanhMuc, cboMauSac, cboSize, cboThuongHieu});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cboTrangThai, txtGia, txtMaSp, txtSoLuong, txtTenSp});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtMaSp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(cboSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTenSp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(cboMauSac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(cboChatLieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel12)
                    .addComponent(cboDanhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cboTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(cboThuongHieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cboChatLieu, cboDanhMuc, cboMauSac, cboSize, cboThuongHieu});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cboTrangThai, txtGia, txtMaSp, txtSoLuong, txtTenSp});

        tblSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "MaSPCt", "Mã SP", "Mã NV", "Tên SP", "Giá", "Số lượng", "Size", "Màu sắc", "Chất liệu", "Danh mục", "Thương hiệu", "Trạng thái"
            }
        ));
        tblSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSanPhamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSanPham);
        if (tblSanPham.getColumnModel().getColumnCount() > 0) {
            tblSanPham.getColumnModel().getColumn(10).setResizable(false);
        }

        jLabel2.setText("Tìm kiếm");

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Add.png"))); // NOI18N
        btnAdd.setText("Thêm");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Update.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Clean.png"))); // NOI18N
        jButton3.setText("Mới");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/import.png"))); // NOI18N
        jButton4.setText("Exel");

        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTimKiemMouseClicked(evt);
            }
        });

        btnHienThiLai.setText("Hiển thị lại");
        btnHienThiLai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHienThiLaiMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(479, 479, 479)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(38, 38, 38)
                                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnTimKiem)
                                    .addGap(34, 34, 34)
                                    .addComponent(btnHienThiLai)
                                    .addGap(223, 223, 223)
                                    .addComponent(btnAdd)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnSua)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButton3)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButton4))))))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAdd, btnSua, jButton3, jButton4});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd)
                    .addComponent(btnSua)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(btnTimKiem)
                    .addComponent(btnHienThiLai))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAdd, btnSua, jButton3, jButton4});

    }// </editor-fold>//GEN-END:initComponents

    private void LoadDataToTableSanPham() {
        model.setRowCount(0);
        //goi phuong thuc getAllSinhVien() cua SinhVienService de lay du lieu
        ArrayList<SanPhamQuanLy> lst = qlsvsv.getAllSanPham();

        for (SanPhamQuanLy bh : lst) {
            model.addRow(new Object[]{
                bh.getMaSpCt(),
                bh.getMaSp(),
                bh.getMaNv(),
                bh.getTenSp(),
                bh.getGia(),
                bh.getSoLuong(),
                bh.getTenSz(),
                bh.getTenMs(),
                bh.getTenCl(),
                bh.getTenDm(),
                bh.getTenTh(),
                bh.isTrangThai() ? "Đang bán" : "Ngừng bán"
            });
        }

    }

    private void LoadDataToTableSanPham(String ma) {
        model.setRowCount(0);
        //goi phuong thuc getAllSinhVien() cua SinhVienService de lay du lieu
        SanPhamQuanLy bh = qlsvsv.timKiemSanPhamTheoMa(ma);

        model.addRow(new Object[]{
            bh.getMaSpCt(),
            bh.getMaSp(),
            bh.getMaNv(),
            bh.getTenSp(),
            bh.getGia(),
            bh.getSoLuong(),
            bh.getTenSz(),
            bh.getTenMs(),
            bh.getTenCl(),
            bh.getTenDm(),
            bh.getTenTh(),
            bh.isTrangThai() ? "Đang bán" : "Ngừng bán"
        });

    }

    private void showDetails() {
        //Lay Dong dang chon tren table
        int index = tblSanPham.getSelectedRow();
        this.editForm();

        DefaultComboBoxModel modelkt = (DefaultComboBoxModel) cboSize.getModel();
        modelkt.removeAllElements();
        List<Size> listCbbkt = szsv.getAllSize();
        for (Size size : listkt) {
            modelkt.addElement(size);
        }
        modelkt.setSelectedItem(getBySize(tblSanPham.getValueAt(index, 6).toString()));

        //mau sac
        DefaultComboBoxModel modelms = (DefaultComboBoxModel) cboMauSac.getModel();
        modelms.removeAllElements();
        for (MauSac ms : listms) {
            modelms.addElement(ms);
        }
        modelms.setSelectedItem(getByMauSac(tblSanPham.getValueAt(index, 7).toString()));

        //chat lieu
        DefaultComboBoxModel modelcl = (DefaultComboBoxModel) cboChatLieu.getModel();
        modelcl.removeAllElements();
        for (ChatLieu cl : listcl) {
            modelcl.addElement(cl);
        }
        modelcl.setSelectedItem(getByChatLieu(tblSanPham.getValueAt(index, 8).toString()));

        //danh muc
        DefaultComboBoxModel modeldm = (DefaultComboBoxModel) cboDanhMuc.getModel();
        modeldm.removeAllElements();
        for (DanhMuc dm : listdm) {
            modeldm.addElement(dm);
        }
        modeldm.setSelectedItem(getByDanhMuc(tblSanPham.getValueAt(index, 9).toString()));

        //thuong hieu
        DefaultComboBoxModel modelth = (DefaultComboBoxModel) cboThuongHieu.getModel();
        modelth.removeAllElements();
        for (ThuongHieu th : listth) {
            modelth.addElement(th);
        }
        modelth.setSelectedItem(getByThuongHieu(tblSanPham.getValueAt(index, 10).toString()));
    }

    private void editForm() {
        int index = tblSanPham.getSelectedRow();
        String ma = (String) tblSanPham.getValueAt(index, 0);
        SanPhamChiTiet spct = spctsc.timKiemTheoMa(ma);
        this.setDataForm(spct);
//        this.updateStatus();
    }

//    private void updateStatus() {
//        int index = tblSanPham.getSelectedRow();
//        Boolean edit = index >= 0;
//
//        btnAdd.setEnabled(!edit);
//        btnSua.setEnabled(edit);
//    }
    private void setDataForm(SanPhamChiTiet spct) {

        txtMaSp.setText(spct.getMaSP());

        txtTenSp.setText(spct.getSanPham().getTen());
        txtGia.setText(String.valueOf(spct.getGia()));
        txtSoLuong.setText(String.valueOf(spct.getSoLuong()));

        cboSize.setSelectedItem(spct.getSize().getTen());
        cboMauSac.setSelectedItem(spct.getMauSac().getTen());
        cboChatLieu.setSelectedItem(spct.getChatLieu().getTen());
        cboChatLieu.setSelectedItem(spct.getSanPham().getDanhMuc().getTen());
        cboThuongHieu.setSelectedItem(spct.getSanPham().getThuongHieu().getTen());

        cboTrangThai.setSelectedItem(spct.isTrangThai() ? "Đang bán" : "Ngừng bán");
    }

    public Size getBySize(String ten) {
        for (Size o : listkt) {
            if (o.getTen().equalsIgnoreCase(ten)) {
                return new Size(o.getId(), o.getTen());
            }
        }
        return null;
    }

    public ChatLieu getByChatLieu(String ten) {
        for (ChatLieu o : listcl) {
            if (o.getTen().equalsIgnoreCase(ten)) {
                return new ChatLieu(o.getId(), o.getTen());
            }
        }
        return null;
    }

    public DanhMuc getByDanhMuc(String ten) {
        for (DanhMuc o : listdm) {
            if (o.getTen().equalsIgnoreCase(ten)) {
                return new DanhMuc(o.getId(), o.getTen());
            }
        }
        return null;
    }

    public MauSac getByMauSac(String ten) {
        for (MauSac o : listms) {
            if (o.getTen().equalsIgnoreCase(ten)) {
                return new MauSac(o.getId(), o.getTen());
            }
        }
        return null;
    }

    public ThuongHieu getByThuongHieu(String ten) {
        for (ThuongHieu o : listth) {
            if (o.getTen().equalsIgnoreCase(ten)) {
                return new ThuongHieu(o.getId(), o.getTen());
            }
        }
        return null;
    }

    private SanPhamChiTiet getDataForm_spct() {
        SanPhamChiTiet spct = new SanPhamChiTiet();

        spct.setMaSP(txtMaSp.getText());
        boolean check = false;
        try {
            spct.setGia(Double.valueOf(txtGia.getText()));
            check = true;
        } catch (Exception e) {
            check = false;
            JOptionPane.showMessageDialog(this, "Giá phải là số!");

        }
        if (Double.parseDouble(txtGia.getText()) < 0) {
            check = false;
            JOptionPane.showMessageDialog(this, "Giá phải lớn hơn 0!");
        }
        try {
            spct.setSoLuong(Integer.valueOf(txtSoLuong.getText()));
            check = true;
        } catch (Exception e) {
            check = false;
            JOptionPane.showMessageDialog(this, "Số lượng phải là số!");
        }

        if (Integer.parseInt(txtSoLuong.getText()) < 0) {
            check = false;
            JOptionPane.showMessageDialog(this, "Số lượng phải lớn hơn 0!");

        }
        if (check = true) {
            String status = (String) cboTrangThai.getSelectedItem();
            Boolean trangThai = status.equals("Đang bán");
            spct.setTrangThai(trangThai);

            ChatLieu cl = (ChatLieu) cboChatLieu.getSelectedItem();
            spct.setId_chatLieu(cl.getId());
            Size size = (Size) cboSize.getSelectedItem();
            spct.setId_size(size.getId());
            MauSac ms = (MauSac) cboMauSac.getSelectedItem();
            spct.setId_mauSac(ms.getId());
            return spct;
        }
        return null;
    }

    private SanPham getData_SP() {
        SanPham sp = new SanPham();

        sp.setMaSp(txtMaSp.getText());
        sp.setTen(txtTenSp.getText());
        sp.setMaNV("PH41905");
        Date currentDate = new Date();
        sp.setNgayThem(new java.sql.Date(currentDate.getTime()));
        ThuongHieu th = (ThuongHieu) cboThuongHieu.getSelectedItem();
        sp.setId_th(th.getId());
        DanhMuc dm = (DanhMuc) cboDanhMuc.getSelectedItem();
        sp.setId_dm(dm.getId());
        return sp;
    }

    private void insert_sp_spct() {
        int check = JOptionPane.showConfirmDialog(this, "Xác nhận thêm dữ liệu?");
        if (check != 0) {
            return;
        }

        try {
            //Check loi rong , so , mien
            SanPham sv = getData_SP();
            SanPhamChiTiet spct = getDataForm_spct();
            if (spsv.addSanPham(sv) != null && spctsc.addSanPhamCt(spct) != null) {
                JOptionPane.showMessageDialog(this, "Them Thanh Cong");
                LoadDataToTableSanPham();
            } else {
                JOptionPane.showMessageDialog(this, "Ko thanh cong");
            }
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(this, "Loi nut them");
        }

    }

    private void update() {
        int check = JOptionPane.showConfirmDialog(this, "Xác sửa dữ liệu?");
        if (check != 0) {
            return;
        }

        try {
            //Check loi rong , so , mien
            SanPham sv = getData_SP();
            SanPhamChiTiet spct = getDataForm_spct();
            if (spsv.updateSanPham(sv) != null && spctsc.updateSanPhamChiTiet(spct) != null) {
                JOptionPane.showMessageDialog(this, "Sửa thành công");
                LoadDataToTableSanPham();

            } else {
                JOptionPane.showMessageDialog(this, "Sủa không thành công");
            }
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(this, "Lỗi nút sửa");
        }

    }

    private void txtSoLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoLuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoLuongActionPerformed

    private void tblSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSanPhamMouseClicked
        // TODO add your handling code here:
        showDetails();
    }//GEN-LAST:event_tblSanPhamMouseClicked

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        insert_sp_spct();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        update();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnTimKiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTimKiemMouseClicked
        // TODO add your handling code here:
        String getMa = txtTimKiem.getText();
        LoadDataToTableSanPham(getMa);
    }//GEN-LAST:event_btnTimKiemMouseClicked

    private void btnHienThiLaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHienThiLaiMouseClicked
        // TODO add your handling code here:
        LoadDataToTableSanPham();
    }//GEN-LAST:event_btnHienThiLaiMouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        txtMaSp.setText("");
        txtTenSp.setText("");
        txtGia.setText("");
        txtSoLuong.setText("");
    }//GEN-LAST:event_jButton3MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnHienThiLai;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JComboBox<String> cboChatLieu;
    private javax.swing.JComboBox<String> cboDanhMuc;
    private javax.swing.JComboBox<String> cboMauSac;
    private javax.swing.JComboBox<String> cboSize;
    private javax.swing.JComboBox<String> cboThuongHieu;
    private javax.swing.JComboBox<String> cboTrangThai;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSanPham;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtMaSp;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTenSp;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
